service: lambda-demo

custom:
  bucket: elchetz-tmp
  folder: lambda-demo

provider:
  name: aws
  profile: personal
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${self:custom.bucket}/${self:custom.folder}/*"

functions:
  save:
    handler: handler.save
    events:
      - http: POST save
        # path: save
        # method: post
    environment:
      BUCKET: "${self:custom.bucket}"
      FOLDER: "${self:custom.folder}"
